# Generated by Django 5.2.4 on 2025-09-03 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_event_image_alter_event_organame_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_id', models.CharField(max_length=20, unique=True)),
                ('user_name', models.CharField(max_length=150)),
                ('name', models.CharField(max_length=150)),
                ('std_id', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('item_type', models.CharField(choices=[('events', 'Events')], max_length=20)),
                ('item_id', models.PositiveIntegerField()),
                ('item_name', models.CharField(max_length=255)),
                ('booking_date', models.DateField()),
                ('status', models.CharField(default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
